name: Managing Secrets Commit & Push

on:
  workflow_dispatch:  # Allows manual trigger of the workflow
  push:  # Triggers on push to any branch

jobs:
  print_repo_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Read Repository Masked Secret
        run: echo "${{ secrets.dev_api_key }}"  # Correct syntax for accessing 'dev_api_key' secret

      - name: Read Repository Secret Content
        run: echo "${{ secrets.dev_api_key }}" | sed 's/./&/g'  # Using sed to manipulate the secret content

      - name: Read PRODUCTION Secret Content
        run: echo "${{ secrets.prod_api_key }}" | sed 's/./&/g'  # Correct syntax for accessing 'prod_api_key' secret

  print_environment_secrets:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Read Repository Secret Content
        run: echo "${{ secrets.dev_api_key }}" | sed 's/./&/g'  # Repeated access to dev secret

      - name: Read PRODUCTION Secret Content
        run: echo "${{ secrets.prod_api_key }}" | sed 's/./&/g'  # Repeated access to prod secret


  print_organization_secrets:
    runs-on: ubuntu-latest  # Specify the environment to run the job

    steps:
      - name: Read PRODUCTION Secret Content
        run: echo "${{ secrets.prod_api_key }}" | sed 's/./&/g'  # Correct secret name format and command

      - name: Read AWS ACCESS KEY Secret Content
        run: echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | sed 's/./&/g'  # Correct secret name and syntax

      - name: Read PLATFORM PASSWORD Secret Content
        run: echo "${{ secrets.PLATFORM_SECRET }}" | sed 's/./&/g'  # Correct secret access